### ISSUE TITLE
RemoteSyslog5424Appender should ship named environment variables

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/log4net.Appenders.Contrib#10]
Should be able to configure which machine environment variables should be shipped along with logs forwarded by the `RemoteSyslog5424Appender`

```xml
<appender name="RemoteAppender" type="log4net.Appenders.Contrib.RemoteSyslog5424Appender,log4net.Appenders.Contrib">
      <AppName>log4net.Appenders.Contrib.SampleApp</AppName>
     <field key="environment" value="$HOSTNAME" />
     <field key="user" value="$USER" />
...snip...
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message" />
      </layout>
    </appender>
```

`$HOSTNAME` and `$USER` should be resolved to the corresponding values pulled from the local environment

**Comment by fandrei** [comment]
@mrdavidlaing, I struggle trying to make log4net parse params in this format. Do you mind if I use a different syntax, for example `<Field>environment=$HOSTNAME</Field>`?

**Comment by mrdavidlaing** [comment]
@fandrei - a different format is fine.

**Comment by fandrei** [comment]
@mrdavidlaing, how does it look? https://github.com/cityindex/log4net.Appenders.Contrib/pull/18

Sample output:
```
162 <14>1 2015-07-27T05:22:58.882878Z Andrei-PC log4net.Appenders.Contrib.SampleApp - - [fields@48665 environment="$HOSTNAME"] 2_402045bc-ac2e-4cdb-b4ff-d019efa8efcb
```
