### ISSUE TITLE
Program using RemoteSyslog5424Appender doesn't shut down unless log.Logger.Repository.Shutdown() called

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/log4net.Appenders.Contrib#13]
This simple console program:
```csharp
namespace ConsoleApplication1
{
 class Program
 {
	static void Main(string[] args)
	{
	 XmlConfigurator.Configure();

	 var log = LogManager.GetLogger(typeof(Program));
	 log.Debug("Pre-Hello world");
	 log.Info("Hello world");
	 log.Error("Eek!");

	 //log.Logger.Repository.Shutdown();
	}
 }
}
```
fails to shutdown unless `//log.Logger.Repository.Shutdown();` is uncommented.

A manual call to log.Logger.Repository.Shutdown(); shouldn't be necessary

**Comment by fandrei** [comment]
@mrdavidlaing, I've tried to set Background=true as @ewilde suggested, but there are some ramifications. With this property set the application always shuts down successfully, but it doesn't send any data unless you call log.Logger.Repository.Shutdown() explicitly. log4net is using AppDomain.ProcessExit event to close appenders before exiting, but total time for processing is limited to just 2 seconds by runtime, and this time is not enough to flush data to the server.
