### ISSUE TITLE
Throttle messages that can be enqueue by the RemoteSyslog5424Appender to prevent OutOfMemory exceptions

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/log4net.Appenders.Contrib#14]
In cases where messages are being enqueued for sending via the `RemoteSyslog5424Appender` at a rate faster than they can be sent, it is possible for the queue to grow until an OutOfMemory exception is thrown.

```
2015-07-19 05:59:55,461 [9] ERROR RemoteSyslog5424AppenderDiagLogger - System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Concat(String str0, String str1)
   at System.String.Concat(Object arg0, Object arg1)
   at log4net.Appenders.Contrib.RemoteSyslog5424Appender.Append(LoggingEvent loggingEvent) in c:\Dev\log4net.Appenders.Contrib\src\log4net.Appenders.Contrib\RemoteSyslog5424Appender.cs:line 107
```

It would be better if the `RemoteSyslog5424Appender` stopped accepting new messages at some point (probably related to the amount of consumed memory)

**Comment by mrdavidlaing** [comment]
@ewilde What is a "reasonable" upper limit of memory consumed by the `RemoteSyslog5424Appender` in the City Index context?  250MB?

**Comment by ewilde** [comment]
@mrdavidlaing seems reasonable. `RemoteSyslog5424Appender` is only going to be for environments where installing the logshipper is not possible?

I guess using the logshipper we wouldn't be in a possible where we potentially discard messages

**Comment by mrdavidlaing** [comment]
> RemoteSyslog5424Appender is only going to be for environments where installing the logshipper is not possible, i.e. G2Shell?

Currently that seems to be the case.

> I guess using the logshipper we wouldn't be in a positon where we potentially discard messages

yes - if the logs get written to file, they should (eventually) get shipped

**Comment by fandrei** [comment]
@mrdavidlaing, should it just ignore all new messages? I'd send a notification message that the message queue is overfull.

Calculating total size of message queue in bytes will be a quite time consuming operation.

**Comment by mrdavidlaing** [comment]
@fandrei - yes - I think dropping new messages and logging a WARN to the `RemoteSyslog5424AppenderDiagLogger` logger is the "right" behaviour

How about we just assume that the "average" log message is 250 bytes, and thus limit the queue to `1024`?

That should hopefully balance performance with not using too much memory

**Comment by fandrei** [comment]
@mrdavidlaing, does this look like a right approach to you? https://github.com/cityindex/log4net.Appenders.Contrib/commit/1820237a322e9ad817490d2422327012a30be1c4
