### ISSUE TITLE
Log messages in JSON

### ISSUE THREAD

**Issue by ewilde** [cityindex/log4net.Appenders.Contrib#19]
# Summary
To allow clients to easily send custom fields to logsearch it should be possible to ship logs using JSON

# Details
@mrdavidlaing suggested a similar approach has been used in LSS

>The route I’d advise investigating is having Log4Net write your message data as JSON (via some kind of custom PatternLayout), and configuring  the log4net.Appenders.Contrib.RemoteSyslog5242Appender with<Field>type=json<Field> so that the logsearch parsers parse log message as JSON.
 
> We’ve gone down this route with LogsearchShipper, so there might be some ideas or code to extract from there.
 
> https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/EdbDataFormatter.cs#L64
https://github.com/cityindex/LogSearchShipper/blob/master/src/LogSearchShipper/Log4net/JsonLayout.cs

# Implementation
* Extract json code from LSS (duplicate for now)
* Update sample application https://github.com/cityindex/log4net.Appenders.Contrib/blob/master/src/SampleApp/Program.cs#L12
Thoughts?

**Comment by fandrei** [comment]
@ewilde, @mrdavidlaing sample message:

```
256 <11>1 2015-08-18T06:39:13.934830Z Andrei-PC log4net.Appenders.Contrib.SampleApp - - [fields@0 type="json" environment="DEV" user="Andrei"] {"Message":"I’m broken. Please show this to someone who can fix can fix (0_8dfbc0f3-d686-4af9-b358-5328d031bf47)"}
```
Does it look right to you?

**Comment by fandrei** [comment]
@mrdavidlaing, it seems there is a problem parsing such messages. When I send a message formatted like a sample above, its parsing fails with a _jsonparsefailure tag. I recon it's happening because this message contains both RFC 5424 structured data and JSON data. And when I omit structured data and send just JSON, it's not parsed as JSON because of missing "type" field.
I wonder how can we fix this problem?

**Comment by fandrei** [comment]
@ewilde, @mrdavidlaing it looks like this parsing problem is purely server-side, so we could merge this feature and let the users start adding it to their code.
