### ISSUE TITLE
Async logging

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/log4net.Appenders.Contrib#6]
Log4Net appears to be an synchronous framework by default.

This means that when using the RemoteSyslog5424Appender the calling code will be blocked until the syslog message is sent over the network.

We should implement some kind of queueing mechanism so that logging to the RemoteSyslog5424Appender is non blocking to the calling code.

**Comment by mrdavidlaing** [comment]
https://github.com/cjbhaines/Log4Net.Async provides some reference code on how to do this.

**Comment by fandrei** [comment]
@mrdavidlaing, done
