### ISSUE TITLE
Exponential backoff on network reconnects

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/log4net.Appenders.Contrib#7]
During a network reconnect we should wait for an exponentially increasing time between each connection attempt, before giving up.

We'll need to introduce async logging - #6 - before implementing this

**Comment by fandrei** [comment]
@mrdavidlaing, I think it's better to limit the maximum waiting period to some sensible value. Infinite period growth can lead to days and weeks before the next connection attempt.

**Comment by mrdavidlaing** [comment]
Fine by me.  Maybe exponential back off up to 10 min.

:D

On 18 Jun 2015, at 11:35, Andrei Faber <notifications@github.com<mailto:notifications@github.com>> wrote:


@mrdavidlaing<https://github.com/mrdavidlaing>, I think it's better to limit the maximum waiting period to some sensible value. Infinite period growth can lead to days and weeks before the next connection attempt.

—
Reply to this email directly or view it on GitHub<https://github.com/cityindex/log4net.Appenders.Contrib/issues/7#issuecomment-113103016>.

This email is intended only for the use of the individual or entity to which it is addressed and may contain information that is confidential, subject to copyright or which constitutes a trade secret. You should not copy it for any purpose or disclose its contents to any person. GAIN Capital UK Ltd has taken reasonable precautions to minimise the risk of transmitting software viruses but we advise you to carry out your own virus checks on any attachment to this message. We cannot accept any liability for any loss or damage resulting from any software viruses. If you receive this email in error, please telephone our postmaster on +44 20 7550 8500 or email postmaster@cityindex.co.uk and delete all copies on your system.

GAIN Capital UK Ltd is authorised and regulated by the Financial Conduct Authority.  FCA Register Number: 113942. Registered Office: Park House, 16 Finsbury Circus, London, EC2M 7EB. Registered in England and Wales, number: 1761813.

**Comment by ewilde** [comment]
@fandrei @mrdavidlaing I was thinking maybe [Polly](https://github.com/michael-wolfenden/Polly) might be able to help us here. I've not used the library yet, but have been wanting to for a long time. This seems like a perfect fit.


```cs
// Retry a specified number of times, using a function to 
// calculate the duration to wait between retries based on 
// the current retry attempt (allows for exponential backoff)
// In this case will wait for
//  1 ^ 2 = 2 seconds then
//  2 ^ 2 = 4 seconds then
//  3 ^ 2 = 8 seconds then
//  4 ^ 2 = 16 seconds then
//  5 ^ 2 = 32 seconds
... stop at 10 minutes

Policy
  .Handle<DivideByZeroException>()
  .WaitAndRetry(5, retryAttempt => 
    TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)) 
  );
```

**Comment by mrdavidlaing** [comment]
That would certainly fulfill my readability request.

Would it make testing easier / not necessary?  If we can trust the library, I'm nevery sure of the value of writing unit tests to verify that we call the library with the right parameters...

**Comment by ewilde** [comment]
agree strongly. no value in testing a call to a component.

We could create a new integration test project and simulate an actual outage, then bring back the network and check the reconnection is established.

We've been doing a lot of this type of testing with the Carbon messaging project. It's been quite invaluable.

**Comment by fandrei** [comment]
@ewilde, @mrdavidlaing one possible problem using Polly is how to interrupt execution before the waiting period ends; it's necessary when the host process is about to exit and we need to flush data and exit the cleanup method as soon as possible.

wrt the need of integration testing - absolutely agreed. I wonder how did you simulate network outages in that project?

**Comment by fandrei** [comment]
@ewilde, @mrdavidlaing wrt simulation of network outages in the integration tests - I'd use a mock server. Do you have better ideas?

**Comment by ewilde** [comment]
@fandrei yes a mock server or real server sounds like a good idea. Not sure how easy it is to get a real syslog server orchestrated from an integration test.

I started looking at using Kiwi syslog server in an integration test http://www.kiwisyslog.com/products/kiwi-syslog-server/product-overview.aspx looks like it also supports TLS (http://www.kiwisyslog.com/help/syslog/index.html?inputs___secure_tls_syslog.htm)

But maybe a mock server is easier
